### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by schmutzre** [schmutzre/HIVTB_comparison#1]
- [x] Include new TB drugs from the updated table
- [x] Check if Aalen Johansen is valid
- [x] See ipad notes for eda updates
- [x] Start imputation
- [x] Clean the repo and comment 
- [x] Use new definition for who stage (see Teams message Lukas)
- [x] Implement new ART-naive definition in RSA and Switzerland
- [x] Evtl. consider further filtering out patients in RSA
- [x] Run analysis again and update the abstract
